#!/usr/bin/env bash
#
# Generate .env with random passwords for the demo environment.
#
# Usage:
#   ./setup.sh              # generate .env with random passwords
#   ./setup.sh --print      # print passwords without writing .env
#
# You can also set passwords via environment variables before running:
#   CLICKHOUSE_DEFAULT_PASSWORD=mypass CLICKHOUSE_READONLY_PASSWORD=ropass ./setup.sh
#
set -euo pipefail

cd "$(dirname "$0")"

PRINT_ONLY=false
if [[ "${1:-}" == "--print" ]]; then
  PRINT_ONLY=true
fi

# Generate a random password (32 chars, alphanumeric)
generate_password() {
  openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c 32
}

# Use env vars if set, otherwise generate random passwords
DEFAULT_PASSWORD="${CLICKHOUSE_DEFAULT_PASSWORD:-$(generate_password)}"
READONLY_PASSWORD="${CLICKHOUSE_READONLY_PASSWORD:-$(generate_password)}"
GRAFANA_PASSWORD="${GRAFANA_ADMIN_PASSWORD:-$(generate_password)}"

if $PRINT_ONLY; then
  echo "CLICKHOUSE_DEFAULT_PASSWORD=$DEFAULT_PASSWORD"
  echo "CLICKHOUSE_READONLY_PASSWORD=$READONLY_PASSWORD"
  echo "GRAFANA_ADMIN_PASSWORD=$GRAFANA_PASSWORD"
  exit 0
fi

if [[ -f .env ]]; then
  echo "WARNING: .env already exists. Overwrite? [y/N]"
  read -r answer
  if [[ ! "$answer" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
  fi
fi

cat > .env <<EOF
# Generated by setup.sh — DO NOT commit this file
# Regenerate: rm .env && ./setup.sh

# ─── ClickHouse default user (admin) ───
CLICKHOUSE_DEFAULT_PASSWORD=$DEFAULT_PASSWORD

# ─── ClickHouse read-only user (externally accessible) ───
CLICKHOUSE_READONLY_PASSWORD=$READONLY_PASSWORD

# ─── Grafana admin ───
GRAFANA_ADMIN_PASSWORD=$GRAFANA_PASSWORD
EOF

echo "============================================"
echo "  .env created with generated passwords"
echo "============================================"
echo ""
echo "  Default user (admin):  $DEFAULT_PASSWORD"
echo "  Read-only user:        $READONLY_PASSWORD"
echo "  Grafana admin:         $GRAFANA_PASSWORD"
echo ""
echo "  Start the cluster:"
echo "    docker compose up -d"
echo ""
echo "  Connect (admin, from server):"
echo "    docker exec -it tracehouse-demo-ch-s1r1 clickhouse-client --password '$DEFAULT_PASSWORD'"
echo ""
echo "  Connect (read-only, remote):"
echo "    curl -u 'read_only:$READONLY_PASSWORD' https://<server>:8443/ --insecure -d 'SELECT 1'"
echo ""
