/**
 * 4-node ClickHouse cluster mimicking Altinity operator topology.
 *
 * Topology: 2 shards × 2 replicas + 1 ClickHouse Keeper node.
 *
 * Cluster definitions (mirroring real Altinity operator chop-generated-remote_servers.xml):
 *   dev:            4 entries — 2 shards × 2 replicas, internal_replication=true
 *   all-sharded:    4 entries — ch1, ch2, ch3, ch4 (each node = 1 shard)
 *   all-replicated: 4 entries — 1 shard, 4 replicas, internal_replication=true
 *   all-clusters:   4 entries — same as dev (2 shards × 2 replicas)
 */

import { GenericContainer, Network, Wait, type StartedNetwork, type StartedTestContainer } from 'testcontainers';
import { createClient, type ClickHouseClient } from '@clickhouse/client';
import { ClusterTestAdapter } from './cluster-container.js';
import { CH_IMAGE } from './constants.js';

const CH_USER = 'default';
const CH_PASSWORD = 'test';

// Reuse the same Keeper config as the 2-node setup
const KEEPER_CONFIG = `<?xml version="1.0"?>
<clickhouse>
  <listen_host>0.0.0.0</listen_host>
  <keeper_server>
    <tcp_port>9181</tcp_port>
    <server_id>1</server_id>
    <raft_configuration>
      <server>
        <id>1</id>
        <hostname>keeper</hostname>
        <port>9234</port>
      </server>
    </raft_configuration>
  </keeper_server>
</clickhouse>`;

/**
 * Generate ClickHouse config for a node in the 4-node Altinity-like cluster.
 *
 * Mirrors the real Altinity operator output (chop-generated-remote_servers.xml):
 * all clusters list all 4 nodes — dev has 2 shards × 2 replicas with
 * internal_replication=true, all-sharded has each node as its own shard, etc.
 */
function altinityChConfig(replicaName: string, shard: string, replica: string): string {
  return `<?xml version="1.0"?>
<clickhouse>
  <listen_host>0.0.0.0</listen_host>
  <interserver_http_host>${replicaName}</interserver_http_host>
  <interserver_http_credentials>
    <user>interserver</user>
    <password>interserver_secret</password>
  </interserver_http_credentials>
  <remote_servers>
    <!-- User-specified cluster: 2 shards × 2 replicas -->
    <dev>
      <secret>cluster_secret</secret>
      <shard>
        <internal_replication>true</internal_replication>
        <replica><host>ch1</host><port>9000</port></replica>
        <replica><host>ch2</host><port>9000</port></replica>
      </shard>
      <shard>
        <internal_replication>true</internal_replication>
        <replica><host>ch3</host><port>9000</port></replica>
        <replica><host>ch4</host><port>9000</port></replica>
      </shard>
    </dev>
    <!-- Autogenerated: all-replicated (1 shard, 4 replicas) -->
    <all-replicated>
      <secret>cluster_secret</secret>
      <shard>
        <internal_replication>true</internal_replication>
        <replica><host>ch1</host><port>9000</port></replica>
        <replica><host>ch2</host><port>9000</port></replica>
        <replica><host>ch3</host><port>9000</port></replica>
        <replica><host>ch4</host><port>9000</port></replica>
      </shard>
    </all-replicated>
    <!-- Autogenerated: all-sharded (each node = 1 shard) -->
    <all-sharded>
      <secret>cluster_secret</secret>
      <shard><internal_replication>false</internal_replication><replica><host>ch1</host><port>9000</port></replica></shard>
      <shard><internal_replication>false</internal_replication><replica><host>ch2</host><port>9000</port></replica></shard>
      <shard><internal_replication>false</internal_replication><replica><host>ch3</host><port>9000</port></replica></shard>
      <shard><internal_replication>false</internal_replication><replica><host>ch4</host><port>9000</port></replica></shard>
    </all-sharded>
    <!-- Autogenerated: all-clusters (same as dev) -->
    <all-clusters>
      <secret>cluster_secret</secret>
      <shard>
        <internal_replication>true</internal_replication>
        <replica><host>ch1</host><port>9000</port></replica>
        <replica><host>ch2</host><port>9000</port></replica>
      </shard>
      <shard>
        <internal_replication>true</internal_replication>
        <replica><host>ch3</host><port>9000</port></replica>
        <replica><host>ch4</host><port>9000</port></replica>
      </shard>
    </all-clusters>
  </remote_servers>
  <zookeeper>
    <node>
      <host>keeper</host>
      <port>9181</port>
    </node>
  </zookeeper>
  <macros>
    <shard>${shard}</shard>
    <replica>${replica}</replica>
    <cluster>dev</cluster>
  </macros>
</clickhouse>`;
}

export interface AltinityClusterContext {
  network: StartedNetwork;
  keeper: StartedTestContainer;
  /** Shard 1, Replica 1 */
  ch1: StartedTestContainer;
  /** Shard 1, Replica 2 */
  ch2: StartedTestContainer;
  /** Shard 2, Replica 1 */
  ch3: StartedTestContainer;
  /** Shard 2, Replica 2 */
  ch4: StartedTestContainer;
  clients: ClickHouseClient[];
  adapters: ClusterTestAdapter[];
}

function startChNode(
  image: string,
  network: StartedNetwork,
  alias: string,
  shard: string,
  replica: string,
): Promise<StartedTestContainer> {
  return new GenericContainer(image)
    .withNetwork(network)
    .withNetworkAliases(alias)
    .withEnvironment({ CLICKHOUSE_USER: CH_USER, CLICKHOUSE_PASSWORD: CH_PASSWORD })
    .withCopyContentToContainer([{
      content: altinityChConfig(alias, shard, replica),
      target: '/etc/clickhouse-server/config.d/cluster.xml',
    }])
    .withExposedPorts(8123, 9000)
    .withWaitStrategy(Wait.forHttp('/ping', 8123).forStatusCode(200))
    .withStartupTimeout(60_000)
    .start();
}

/**
 * Start a 4-node ClickHouse cluster mimicking Altinity operator topology.
 *
 * All clusters (dev, all-sharded, all-replicated, all-clusters) list all 4 nodes.
 * The `dev` cluster has 2 shards × 2 replicas with internal_replication=true.
 */
export async function startAltinityCluster(): Promise<AltinityClusterContext> {
  const network = await new Network().start();

  const keeper = await new GenericContainer(CH_IMAGE)
    .withNetwork(network)
    .withNetworkAliases('keeper')
    .withEnvironment({ CLICKHOUSE_USER: CH_USER, CLICKHOUSE_PASSWORD: CH_PASSWORD })
    .withCopyContentToContainer([{
      content: KEEPER_CONFIG,
      target: '/etc/clickhouse-server/config.d/keeper.xml',
    }])
    .withExposedPorts(8123, 9181)
    .withWaitStrategy(Wait.forHttp('/ping', 8123).forStatusCode(200))
    .withStartupTimeout(60_000)
    .start();

  // Start all 4 CH nodes in parallel
  //   ch1: shard 01, replica ch1
  //   ch2: shard 01, replica ch2
  //   ch3: shard 02, replica ch3
  //   ch4: shard 02, replica ch4
  const [ch1, ch2, ch3, ch4] = await Promise.all([
    startChNode(CH_IMAGE, network, 'ch1', '01', 'ch1'),
    startChNode(CH_IMAGE, network, 'ch2', '01', 'ch2'),
    startChNode(CH_IMAGE, network, 'ch3', '02', 'ch3'),
    startChNode(CH_IMAGE, network, 'ch4', '02', 'ch4'),
  ]);

  const containers = [ch1, ch2, ch3, ch4];
  const clients = containers.map(c => createClient({
    url: `http://${c.getHost()}:${c.getMappedPort(8123)}`,
    username: CH_USER,
    password: CH_PASSWORD,
  }));
  const adapters = clients.map(c => new ClusterTestAdapter(c));

  // Wait for the `dev` cluster to be visible (should show 4 entries: 2 shards × 2 replicas)
  await waitForAltinityCluster(clients[0]);

  return { network, keeper, ch1, ch2, ch3, ch4, clients, adapters };
}

/** Wait until system.clusters shows the `dev` cluster with 4 nodes (2 shards × 2 replicas). */
async function waitForAltinityCluster(client: ClickHouseClient, timeoutMs = 60_000): Promise<void> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    try {
      const result = await client.query({
        query: `SELECT cluster, count() AS cnt FROM system.clusters WHERE cluster = 'dev' GROUP BY cluster`,
        format: 'JSONEachRow',
      });
      const rows = await result.json<{ cluster: string; cnt: string }>();
      if (rows.length > 0 && Number(rows[0].cnt) >= 4) return;
    } catch {
      // Retry — server may still be starting
    }
    await new Promise(r => setTimeout(r, 2000));
  }
  throw new Error('Altinity cluster did not become ready within timeout');
}

/** Tear down the 4-node cluster. */
export async function stopAltinityCluster(ctx: AltinityClusterContext): Promise<void> {
  for (const client of ctx.clients) await client.close();
  await ctx.ch1.stop();
  await ctx.ch2.stop();
  await ctx.ch3.stop();
  await ctx.ch4.stop();
  await ctx.keeper.stop();
  await ctx.network.stop();
}
