/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/create-plugin`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.com/developers/plugin-tools/how-to-guides/extend-configurations#extend-the-webpack-config
 */

import CopyWebpackPlugin from 'copy-webpack-plugin';
import ESLintPlugin from 'eslint-webpack-plugin';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
import path from 'path';
import ReplaceInFileWebpackPlugin from 'replace-in-file-webpack-plugin';
import TerserPlugin from 'terser-webpack-plugin';
import webpack, { type Configuration } from 'webpack';
import LiveReloadPlugin from 'webpack-livereload-plugin';
import VirtualModulesPlugin from 'webpack-virtual-modules';
import { mergeWithRules } from 'webpack-merge';

import { BuildModeWebpackPlugin } from './BuildModeWebpackPlugin.ts';
import { FixSourceMapsPlugin } from './FixSourceMapsPlugin.ts';
import { DIST_DIR, SOURCE_DIR } from '../bundler/constants.ts';
import { getCPConfigVersion, getEntries, getPackageJson, getPluginJson, hasReadme, isWSL } from '../bundler/utils.ts';
import { externals } from '../bundler/externals.ts';
import { copyFilePatterns } from '../bundler/copyFiles.ts';

const pluginJson = getPluginJson();
const cpVersion = getCPConfigVersion();
const pluginVersion = getPackageJson().version;
const logoPaths = Array.from(new Set([pluginJson.info?.logos?.large, pluginJson.info?.logos?.small])).filter(Boolean);
const screenshotPaths = pluginJson.info?.screenshots?.map((s: { path: string }) => s.path) || [];
const createVirtualPublicPathPlugin = () => new VirtualModulesPlugin({
  'node_modules/grafana-public-path.js': `
import amdMetaModule from 'amd-module';

__webpack_public_path__ =
  amdMetaModule && amdMetaModule.uri
    ? amdMetaModule.uri.slice(0, amdMetaModule.uri.lastIndexOf('/') + 1)
    : 'public/plugins/${pluginJson.id}/';
`,
});

export type Env = {
  [key: string]: true | string | Env;
};

const repoRoot = path.resolve(process.cwd(), '..');

const config = async (env: Env): Promise<Configuration[]> => {
  const baseConfig: Configuration = {
    cache: {
      type: 'filesystem',
      buildDependencies: {
        config: [path.resolve(process.cwd(), '.config', 'webpack', 'webpack.config.ts')],
      },
    },

    context: path.join(process.cwd(), SOURCE_DIR),

    devtool: false,

    entry: await getEntries(),

    externals,

    experiments: {
      asyncWebAssembly: true,
    },

    mode: env.production ? 'production' : 'development',

    module: {
      rules: [
        {
          test: /src\/(?:.*\/)?module\.tsx?$/,
          use: [
            {
              loader: 'imports-loader',
              options: {
                imports: `side-effects grafana-public-path`,
              },
            },
          ],
        },
        {
          exclude: /(node_modules)/,
          test: /\.[tj]sx?$/,
          use: {
            loader: 'swc-loader',
            options: {
              jsc: {
                baseUrl: path.resolve(process.cwd(), SOURCE_DIR),
                target: 'es2015',
                loose: false,
                parser: {
                  syntax: 'typescript',
                  tsx: true,
                  decorators: false,
                  dynamicImport: true,
                },
                transform: {
                  react: { runtime: 'automatic' },
                },
              },
            },
          },
        },
        {
          test: /\.css$/,
          use: [
            'style-loader',
            'css-loader',
            {
              loader: 'postcss-loader',
              options: {
                postcssOptions: {
                  config: path.resolve(process.cwd(), 'postcss.config.cjs'),
                },
              },
            },
          ],
        },
        {
          test: /\.s[ac]ss$/,
          use: ['style-loader', 'css-loader', 'sass-loader'],
        },
        {
          test: /\.(png|jpe?g|gif|svg)$/,
          type: 'asset/resource',
          generator: {
            filename: Boolean(env.production) ? '[hash][ext]' : '[file]',
          },
        },
        {
          test: /\.(woff|woff2|eot|ttf|otf)(\?v=\d+\.\d+\.\d+)?$/,
          type: 'asset/resource',
          generator: {
            filename: Boolean(env.production) ? '[hash][ext]' : '[file]',
          },
        },
      ],
    },

    optimization: {
      minimize: Boolean(env.production),
      minimizer: [
        new TerserPlugin({
          terserOptions: {
            format: {
              comments: (_, { type, value }) => type === 'comment2' && value.trim().startsWith('[create-plugin]'),
            },
            compress: {
              drop_console: ['log', 'info']
            }
          },
        }),
      ],
    },

    output: {
      clean: {
        keep: new RegExp(`((resourceArena3D|components3d|analytics3d|timeline3d|clusterTopology|replicationTopology|xrayVisualization)-react(18|19)\\.js|.*?_(amd64|arm(64)?)(.exe)?|go_plugin_build_manifest)`),
      },
      filename: '[name].js',
      chunkFilename: env.production ? '[name].[contenthash].js' : '[name].js',
      library: {
        type: 'amd',
      },
      path: path.resolve(process.cwd(), DIST_DIR),
      publicPath: `public/plugins/${pluginJson.id}/`,
      uniqueName: pluginJson.id,
    },

    plugins: [
      new BuildModeWebpackPlugin(),
      createVirtualPublicPathPlugin(),
      new webpack.BannerPlugin({
        banner: `/* [create-plugin] version: ${cpVersion} */
          /* [create-plugin] plugin: ${pluginJson.id}@${pluginVersion} */`,
        raw: true,
        entryOnly: true,
      }),
      new CopyWebpackPlugin({
        patterns: copyFilePatterns,
      }),
      new ReplaceInFileWebpackPlugin([
        {
          dir: DIST_DIR,
          test: [/(^|\/)plugin\.json$/, /(^|\/)README\.md$/],
          rules: [
            {
              search: /\%VERSION\%/g,
              replace: pluginVersion,
            },
            {
              search: /\%TODAY\%/g,
              replace: new Date().toISOString().substring(0, 10),
            },
            {
              search: /\%PLUGIN_ID\%/g,
              replace: pluginJson.id,
            },
          ],
        },
      ]),
      new webpack.SourceMapDevToolPlugin({
        filename: '[file].map',
        noSources: false,
        moduleFilenameTemplate: (info: {
          resourcePath: string;
          absoluteResourcePath?: string;
          allLoaders?: string;
          namespace: string;
        }) => {
          let p = info.resourcePath;
          if (p.startsWith('./')) p = p.substring('./'.length);
          if (p.startsWith('grafana-app-plugin/src/')) p = p.substring('grafana-app-plugin/src/'.length);
          else if (p.startsWith('../../frontend/')) p = p.substring('../../'.length);
          else if (p.startsWith('../../node_modules/')) p = p.substring('../../'.length);
          else if (p.startsWith('../../src/')) {
            const packageName = info.absoluteResourcePath?.includes('/packages/ui-shared/dist/')
              ? 'ui-shared'
              : 'core';
            p = `packages/${packageName}/${p.substring('../../'.length)}`;
          }
          else if (p.startsWith('../../')) p = p.substring('../../'.length);
          else if (p.startsWith('webpack/') || p.startsWith('external ')) p = p;
          else p = p;
          const loaders = info.allLoaders ? `?${info.allLoaders}` : '';
          return `webpack://${info.namespace}/${p}${loaders}`;
        },
      }),
      new webpack.NormalModuleReplacementPlugin(
        /^node:/,
        (resource) => {
          resource.request = resource.request.replace(/^node:/, '');
        }
      ),
      new webpack.IgnorePlugin({ resourceRegExp: /jfrview_bg\.wasm$/ }),
      new webpack.DefinePlugin({
        __BUILD_TIME__: JSON.stringify(new Date().toISOString()),
        __TH_GRAFANA_PLUGIN__: 'true',
      }),
      new FixSourceMapsPlugin(repoRoot),
      ...(env.development ? [
        new LiveReloadPlugin(),
        new ForkTsCheckerWebpackPlugin({
          async: Boolean(env.development),
          issue: {
            include: [{ file: '**/*.{ts,tsx}' }],
          },
          typescript: { configFile: path.join(process.cwd(), 'tsconfig.json') },
        }),
        new ESLintPlugin({
          extensions: ['.ts', '.tsx'],
          lintDirtyModulesOnly: Boolean(env.development),
          failOnError: Boolean(env.production),
        }),
      ] : []),
    ],

    resolve: {
      extensions: ['.ts', '.tsx', '.js', '.jsx', '.css'],
      alias: {
        '@tracehouse/core': path.resolve(repoRoot, 'packages/core/dist'),
        '@tracehouse/ui-shared': path.resolve(repoRoot, 'packages/ui-shared/dist'),
        '@frontend': path.resolve(repoRoot, 'frontend/src'),
        '@react-three/fiber': path.resolve(repoRoot, 'node_modules/@react-three/fiber'),
        '@react-three/drei': path.resolve(repoRoot, 'node_modules/@react-three/drei'),
        [path.resolve(repoRoot, 'frontend/src/components/overview/ResourceArena3D')]:
          path.resolve(process.cwd(), 'src/runtime-compat/ResourceArena3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/3d/Scene3D')]:
          path.resolve(process.cwd(), 'src/runtime-compat/Components3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/3d/PartsVisualization')]:
          path.resolve(process.cwd(), 'src/runtime-compat/Components3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/3d/PipelineVisualization')]:
          path.resolve(process.cwd(), 'src/runtime-compat/Components3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/3d/MergeVisualization')]:
          path.resolve(process.cwd(), 'src/runtime-compat/Components3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/3d/HierarchyVisualization')]:
          path.resolve(process.cwd(), 'src/runtime-compat/Components3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/analytics/ResourceSurface')]:
          path.resolve(process.cwd(), 'src/runtime-compat/Analytics3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/analytics/PatternSurface')]:
          path.resolve(process.cwd(), 'src/runtime-compat/Analytics3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/analytics/StressSurface')]:
          path.resolve(process.cwd(), 'src/runtime-compat/Analytics3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/analytics/charts3d')]:
          path.resolve(process.cwd(), 'src/runtime-compat/Analytics3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/timeline/TimelineChart3D')]:
          path.resolve(process.cwd(), 'src/runtime-compat/Timeline3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/timeline/TimelineChart3DSurface')]:
          path.resolve(process.cwd(), 'src/runtime-compat/Timeline3D.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/cluster/ClusterTopology')]:
          path.resolve(process.cwd(), 'src/runtime-compat/ClusterTopology.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/replication/ReplicationTopology')]:
          path.resolve(process.cwd(), 'src/runtime-compat/ReplicationTopology.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/query/modal/tabs/XRayTab')]:
          path.resolve(process.cwd(), 'src/runtime-compat/XRayTab.tsx'),
        [path.resolve(repoRoot, 'frontend/src/components/query/modal/tabs/XRayVisualization')]:
          path.resolve(process.cwd(), 'src/runtime-compat/XRayVisualization.tsx'),
        [path.resolve(repoRoot, 'frontend/src/stores/connectionStore')]:
          path.resolve(process.cwd(), 'src/stores/connectionStore'),
        [path.resolve(repoRoot, 'frontend/src/providers/ClickHouseProvider')]:
          path.resolve(process.cwd(), 'src/ServiceProvider'),
        [path.resolve(repoRoot, 'frontend/src/hooks/useAppLocation')]:
          path.resolve(process.cwd(), 'src/hooks/useAppLocation.ts'),
        [path.resolve(repoRoot, 'frontend/src/hooks/useUrlState')]:
          path.resolve(process.cwd(), 'src/hooks/useUrlState.ts'),
        [path.resolve(repoRoot, 'frontend/src/utils/urlParams')]:
          path.resolve(process.cwd(), 'src/utils/urlParams.ts'),
        'react-router-dom': path.resolve(process.cwd(), 'src/stubs/react-router-dom.tsx'),
      },
      fallback: {
        stream: false,
        zlib: false,
        crypto: false,
        http: false,
        https: false,
        os: false,
        buffer: false,
        url: false,
        util: false,
        path: false,
        fs: false,
        net: false,
        tls: false,
      },
      modules: [path.resolve(process.cwd(), 'src'), 'node_modules'],
      unsafeCache: true,
    },
  };

  if (isWSL()) {
    baseConfig.watchOptions = {
      poll: 3000,
      ignored: /node_modules/,
    };
  }

  const createRuntime3DConfig = (
    runtime: 'react18' | 'react19',
    name: string,
    entryFile: string
  ): Configuration => ({
    name: `${name}-${runtime}`,
    cache: {
      type: 'filesystem',
      name: `${name}-${runtime}`,
      buildDependencies: {
        config: [path.resolve(process.cwd(), '.config', 'webpack', 'webpack.config.ts')],
      },
    },
    context: process.cwd(),
    devtool: false,
    entry: {
      [`${name}-${runtime}`]: path.resolve(process.cwd(), entryFile),
    },
    externals: runtime === 'react19' ? [...(externals as unknown[]), 'react-dom/client', 'react-dom/server'] : externals,
    experiments: {
      asyncWebAssembly: true,
    },
    mode: env.production ? 'production' : 'development',
    module: baseConfig.module,
    optimization: {
      minimize: Boolean(env.production),
      minimizer: baseConfig.optimization?.minimizer,
    },
    output: {
      filename: '[name].js',
      chunkFilename: env.production ? '[name].[contenthash].js' : '[name].js',
      library: {
        type: 'amd',
      },
      path: path.resolve(process.cwd(), DIST_DIR),
      publicPath: `public/plugins/${pluginJson.id}/`,
      uniqueName: `${pluginJson.id}-${name}-${runtime}`,
    },
    plugins: [
      createVirtualPublicPathPlugin(),
      new webpack.NormalModuleReplacementPlugin(
        /^node:/,
        (resource) => {
          resource.request = resource.request.replace(/^node:/, '');
        }
      ),
      new webpack.IgnorePlugin({ resourceRegExp: /jfrview_bg\.wasm$/ }),
      new webpack.DefinePlugin({
        __BUILD_TIME__: JSON.stringify(new Date().toISOString()),
        __TH_GRAFANA_PLUGIN__: 'true',
      }),
      new FixSourceMapsPlugin(repoRoot),
    ],
    resolve: {
      extensions: ['.ts', '.tsx', '.js', '.jsx', '.css'],
      alias: {
        '@tracehouse/core': path.resolve(repoRoot, 'packages/core/dist'),
        '@tracehouse/ui-shared': path.resolve(repoRoot, 'packages/ui-shared/dist'),
        '@frontend': path.resolve(repoRoot, 'frontend/src'),
        '@react-three/fiber': path.resolve(
          runtime === 'react19' ? repoRoot : process.cwd(),
          runtime === 'react19' ? 'node_modules/@react-three/fiber-react19' : '../node_modules/@react-three/fiber'
        ),
        '@react-three/drei': path.resolve(
          runtime === 'react19' ? repoRoot : process.cwd(),
          runtime === 'react19' ? 'node_modules/@react-three/drei-react19' : '../node_modules/@react-three/drei'
        ),
        [path.resolve(repoRoot, 'frontend/src/stores/connectionStore')]:
          path.resolve(process.cwd(), 'src/stores/connectionStore'),
        [path.resolve(repoRoot, 'frontend/src/providers/ClickHouseProvider')]:
          path.resolve(process.cwd(), 'src/ServiceProvider'),
        [path.resolve(repoRoot, 'frontend/src/hooks/useAppLocation')]:
          path.resolve(process.cwd(), 'src/hooks/useAppLocation.ts'),
        [path.resolve(repoRoot, 'frontend/src/hooks/useUrlState')]:
          path.resolve(process.cwd(), 'src/hooks/useUrlState.ts'),
        [path.resolve(repoRoot, 'frontend/src/utils/urlParams')]:
          path.resolve(process.cwd(), 'src/utils/urlParams.ts'),
        'react-router-dom': path.resolve(process.cwd(), 'src/stubs/react-router-dom.tsx'),
      },
      fallback: baseConfig.resolve?.fallback,
      modules: [path.resolve(process.cwd(), 'src'), 'node_modules'],
      unsafeCache: true,
    },
  });

  return [
    baseConfig,
    createRuntime3DConfig('react18', 'resourceArena3D', 'src/runtime-compat/resourceArena3DEntry.ts'),
    createRuntime3DConfig('react19', 'resourceArena3D', 'src/runtime-compat/resourceArena3DEntry.ts'),
    createRuntime3DConfig('react18', 'components3d', 'src/runtime-compat/components3dEntry.ts'),
    createRuntime3DConfig('react19', 'components3d', 'src/runtime-compat/components3dEntry.ts'),
    createRuntime3DConfig('react18', 'analytics3d', 'src/runtime-compat/analytics3dEntry.ts'),
    createRuntime3DConfig('react19', 'analytics3d', 'src/runtime-compat/analytics3dEntry.ts'),
    createRuntime3DConfig('react18', 'timeline3d', 'src/runtime-compat/timeline3dEntry.ts'),
    createRuntime3DConfig('react19', 'timeline3d', 'src/runtime-compat/timeline3dEntry.ts'),
    createRuntime3DConfig('react18', 'clusterTopology', 'src/runtime-compat/clusterTopologyEntry.ts'),
    createRuntime3DConfig('react19', 'clusterTopology', 'src/runtime-compat/clusterTopologyEntry.ts'),
    createRuntime3DConfig('react18', 'replicationTopology', 'src/runtime-compat/replicationTopologyEntry.ts'),
    createRuntime3DConfig('react19', 'replicationTopology', 'src/runtime-compat/replicationTopologyEntry.ts'),
    createRuntime3DConfig('react18', 'xrayVisualization', 'src/runtime-compat/xrayVisualizationEntry.ts'),
    createRuntime3DConfig('react19', 'xrayVisualization', 'src/runtime-compat/xrayVisualizationEntry.ts'),
  ];
};

export default config;
