/**
 * Utility to clean up ClickHouse error messages for display.
 * Converts raw SQL errors (privilege denied, table not found, etc.)
 * into user-friendly messages.
 *
 * Core services wrap ClickHouse errors in custom Error subclasses
 * (MergeTrackerError, DatabaseExplorerError, etc.) with the original
 * error stored in `.cause`. This module unwraps the full cause chain
 * to find the underlying ClickHouse error code.
 */

export interface FormattedError {
  /** Clean message suitable for display */
  message: string;
  /** Whether this is a permission/access issue (vs. a real error) */
  isPermissionError: boolean;
  /** The system table that caused the issue, if detected */
  table?: string;
}

/**
 * Walk the Error.cause chain and collect all messages into one string.
 * This ensures we find ClickHouse error codes even when they're wrapped
 * in service-level errors like "Failed to get active merges".
 */
function collectErrorMessages(err: unknown): string {
  const parts: string[] = [];
  let current: unknown = err;
  const seen = new Set<unknown>(); // prevent cycles
  while (current && !seen.has(current)) {
    seen.add(current);
    if (current instanceof Error) {
      parts.push(current.message);
      current = current.cause;
    } else if (typeof current === 'string') {
      parts.push(current);
      break;
    } else {
      break;
    }
  }
  return parts.join(' — ');
}

/**
 * Formats a raw ClickHouse error into a user-friendly message.
 * Detects common patterns like Code 497 (privileges) and Code 60 (table not found).
 */
export function formatClickHouseError(raw: string): FormattedError {
  // Code 497 — Not enough privileges
  if (raw.includes('Code 497') || raw.includes('Not enough privileges')) {
    const tableMatch = raw.match(/ON\s+([\w.]+)/);
    const table = tableMatch?.[1];
    return {
      message: table
        ? `Insufficient privileges to access ${table}. Ask your administrator to grant SELECT on this table.`
        : 'Insufficient privileges. Ask your administrator to grant the required permissions.',
      isPermissionError: true,
      table,
    };
  }

  // Code 81 — Database doesn't exist
  if (raw.match(/Code:?\s*81/) || raw.includes('Database') && raw.includes('does not exist')) {
    const dbMatch = raw.match(/Database\s+([\w.`]+)/i);
    const db = dbMatch?.[1]?.replace(/`/g, '');
    const hostMatch = raw.match(/Host:\s*([\w.\-]+)/i);
    const host = hostMatch?.[1];
    const where = host ? ` on ${host}` : ' on this server';
    return {
      message: db
        ? `Database ${db} does not exist${where}.`
        : `Required database does not exist${where}.`,
      isPermissionError: true,
    };
  }

  // Code 60 — Table doesn't exist
  if (raw.match(/Code:?\s*60/) || raw.includes("doesn't exist")) {
    const tableMatch = raw.match(/(?:Table|table)\s+([\w.`]+)/i);
    const table = tableMatch?.[1]?.replace(/`/g, '');
    return {
      message: table
        ? `${table} is not available on this server.`
        : 'Required system table is not available on this server.',
      isPermissionError: true,
      table,
    };
  }

  // Code 516 — Authentication failed
  if (raw.includes('Code 516') || raw.includes('Authentication failed')) {
    return {
      message: 'Authentication failed. Check your connection credentials.',
      isPermissionError: true,
    };
  }

  // Messages generated by our own capability gates (not raw ClickHouse errors)
  if (raw.includes('Insufficient privileges') || raw.includes('not available on this server') || raw.includes('requires') && raw.includes('to be enabled')) {
    return { message: raw, isPermissionError: true };
  }

  return { message: raw, isPermissionError: false };
}

/**
 * Extracts a clean error message from a caught error, then formats it.
 * Unwraps the full cause chain so wrapped service errors (MergeTrackerError,
 * DatabaseExplorerError, etc.) expose the underlying ClickHouse error.
 */
export function formatCaughtError(err: unknown, fallback = 'An error occurred'): FormattedError {
  if (!err) return { message: fallback, isPermissionError: false };
  const combined = collectErrorMessages(err);
  return formatClickHouseError(combined || fallback);
}

/**
 * Extracts a flat error message string from a caught error, unwrapping
 * the cause chain. Use this in catch blocks that store the error as a string
 * (e.g. `setError(extractErrorMessage(err))`), so that downstream
 * formatClickHouseError() can detect ClickHouse error codes.
 */
export function extractErrorMessage(err: unknown, fallback = 'An error occurred'): string {
  if (!err) return fallback;
  return collectErrorMessages(err) || fallback;
}
